## NMF = Not Monday night Football !

In [1]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity
import seaborn as sns
from random import randint
import numpy as np
from sklearn.decomposition import NMF
import pandas as pd
import random
from matplotlib import pyplot as plt
from matplotlib import pyplot as plt
%matplotlib inline
import csv

In [40]:
PATH2 = "ratings.csv"
PATH3 = "movies.csv"
ratings, movies_ind = pd.read_csv(PATH2), pd.read_csv(PATH3)
del ratings['timestamp']
ratings.set_index(['movieId','userId'], inplace=True)
ratings = ratings.unstack(0)
ratings = ratings.fillna(0)
ratings = ratings["rating"]
#ratings = ratings.transpose()


In [41]:
ratings.head(3)

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     0.0     4.0     0.0     0.0     4.0     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10       ...    193565  193567  193571  193573  193579  \
userId                    ...                                             
1           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   

movieId  193581  193583  193585  193587  193609  
userId                                           
1           0.0     0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0     0.0  

[3 rows x 9724 columns]

In [94]:
R = pd.DataFrame(ratings)
# model assumes R ~ PQ'
model = NMF(n_components=5, init='random', random_state=10)
model.fit(R)

P = model.components_  # Movie feature
Q = model.transform(R)  # User features
#print(Q)

#print(model.reconstruction_err_)

nR = np.dot(Q,P) ### Reconstructed model
#print(nR)

# 
query = np.zeros(9724) ###This comes from Glynis array the size = # movies
#query = query.reshape(1,-1)
#t=model.transform(query)
#print(model.transform(query))
#NewR = np.dot(t,Q.T)

In [80]:
print(P.shape)
print(Q.shape)

(5, 9724)
(610, 5)


In [102]:
NewR.shape

(1, 610)

In [91]:
rr= 2
for i in range(0,100):
   # print(i)
    query[i] = rr
    if i == 50:
        rr = 4


In [82]:
query.T

array([2., 2., 2., ..., 0., 0., 0.])

In [87]:
query = query.reshape(1,-1)
t = model.transform(query)
t
print(model.transform(query))
np.dot(t,Q.T)

[[0.         0.00369352 0.15952991 0.         0.01488937]]


array([[3.83109866e-02, 5.59469870e-04, 3.67248028e-04, 7.89575682e-03,
        6.26301501e-02, 1.97633816e-01, 1.23340354e-02, 8.31906279e-02,
        1.77187543e-04, 9.32606267e-04, 6.42823859e-02, 3.98881420e-03,
        0.00000000e+00, 5.98259773e-02, 7.74170192e-03, 8.59254362e-04,
        1.62644776e-02, 3.67604240e-02, 6.26178627e-02, 0.00000000e+00,
        2.40670167e-02, 1.61076435e-04, 1.62301105e-03, 1.88304366e-02,
        2.75968718e-04, 3.97772744e-02, 2.72309536e-02, 1.79958915e-02,
        9.48837650e-03, 2.25627883e-03, 3.03157798e-02, 6.32262390e-02,
        5.40321044e-02, 2.26079211e-04, 3.50968249e-02, 6.62363240e-04,
        4.56693657e-02, 9.68787103e-02, 1.50999763e-02, 9.97990837e-02,
        1.07924850e-03, 8.88468320e-02, 1.47259830e-01, 1.61048700e-02,
        6.23136396e-02, 8.28184139e-02, 1.36553606e-02, 1.71759218e-05,
        6.40069673e-03, 2.18142336e-03, 1.02457767e-02, 2.89597911e-03,
        7.31973495e-04, 4.82399422e-02, 1.15594761e-04, 8.237014